/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardUploadRouteImport } from './routes/dashboard.upload'
import { Route as DashboardReportRouteImport } from './routes/dashboard.report'
import { Route as DashboardPreprocessingRouteImport } from './routes/dashboard.preprocessing'
import { Route as DashboardPhaseFoldingRouteImport } from './routes/dashboard.phase-folding'
import { Route as DashboardParametersRouteImport } from './routes/dashboard.parameters'
import { Route as DashboardDetectionRouteImport } from './routes/dashboard.detection'
import { Route as DashboardClassificationRouteImport } from './routes/dashboard.classification'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUploadRoute = DashboardUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportRoute = DashboardReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPreprocessingRoute = DashboardPreprocessingRouteImport.update({
  id: '/preprocessing',
  path: '/preprocessing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPhaseFoldingRoute = DashboardPhaseFoldingRouteImport.update({
  id: '/phase-folding',
  path: '/phase-folding',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardParametersRoute = DashboardParametersRouteImport.update({
  id: '/parameters',
  path: '/parameters',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDetectionRoute = DashboardDetectionRouteImport.update({
  id: '/detection',
  path: '/detection',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClassificationRoute = DashboardClassificationRouteImport.update({
  id: '/classification',
  path: '/classification',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/classification': typeof DashboardClassificationRoute
  '/dashboard/detection': typeof DashboardDetectionRoute
  '/dashboard/parameters': typeof DashboardParametersRoute
  '/dashboard/phase-folding': typeof DashboardPhaseFoldingRoute
  '/dashboard/preprocessing': typeof DashboardPreprocessingRoute
  '/dashboard/report': typeof DashboardReportRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/classification': typeof DashboardClassificationRoute
  '/dashboard/detection': typeof DashboardDetectionRoute
  '/dashboard/parameters': typeof DashboardParametersRoute
  '/dashboard/phase-folding': typeof DashboardPhaseFoldingRoute
  '/dashboard/preprocessing': typeof DashboardPreprocessingRoute
  '/dashboard/report': typeof DashboardReportRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/classification': typeof DashboardClassificationRoute
  '/dashboard/detection': typeof DashboardDetectionRoute
  '/dashboard/parameters': typeof DashboardParametersRoute
  '/dashboard/phase-folding': typeof DashboardPhaseFoldingRoute
  '/dashboard/preprocessing': typeof DashboardPreprocessingRoute
  '/dashboard/report': typeof DashboardReportRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sitemap.xml'
    | '/dashboard/classification'
    | '/dashboard/detection'
    | '/dashboard/parameters'
    | '/dashboard/phase-folding'
    | '/dashboard/preprocessing'
    | '/dashboard/report'
    | '/dashboard/upload'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/dashboard/classification'
    | '/dashboard/detection'
    | '/dashboard/parameters'
    | '/dashboard/phase-folding'
    | '/dashboard/preprocessing'
    | '/dashboard/report'
    | '/dashboard/upload'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/sitemap.xml'
    | '/dashboard/classification'
    | '/dashboard/detection'
    | '/dashboard/parameters'
    | '/dashboard/phase-folding'
    | '/dashboard/preprocessing'
    | '/dashboard/report'
    | '/dashboard/upload'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/upload': {
      id: '/dashboard/upload'
      path: '/upload'
      fullPath: '/dashboard/upload'
      preLoaderRoute: typeof DashboardUploadRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/report': {
      id: '/dashboard/report'
      path: '/report'
      fullPath: '/dashboard/report'
      preLoaderRoute: typeof DashboardReportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/preprocessing': {
      id: '/dashboard/preprocessing'
      path: '/preprocessing'
      fullPath: '/dashboard/preprocessing'
      preLoaderRoute: typeof DashboardPreprocessingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/phase-folding': {
      id: '/dashboard/phase-folding'
      path: '/phase-folding'
      fullPath: '/dashboard/phase-folding'
      preLoaderRoute: typeof DashboardPhaseFoldingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/parameters': {
      id: '/dashboard/parameters'
      path: '/parameters'
      fullPath: '/dashboard/parameters'
      preLoaderRoute: typeof DashboardParametersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/detection': {
      id: '/dashboard/detection'
      path: '/detection'
      fullPath: '/dashboard/detection'
      preLoaderRoute: typeof DashboardDetectionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/classification': {
      id: '/dashboard/classification'
      path: '/classification'
      fullPath: '/dashboard/classification'
      preLoaderRoute: typeof DashboardClassificationRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardClassificationRoute: typeof DashboardClassificationRoute
  DashboardDetectionRoute: typeof DashboardDetectionRoute
  DashboardParametersRoute: typeof DashboardParametersRoute
  DashboardPhaseFoldingRoute: typeof DashboardPhaseFoldingRoute
  DashboardPreprocessingRoute: typeof DashboardPreprocessingRoute
  DashboardReportRoute: typeof DashboardReportRoute
  DashboardUploadRoute: typeof DashboardUploadRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardClassificationRoute: DashboardClassificationRoute,
  DashboardDetectionRoute: DashboardDetectionRoute,
  DashboardParametersRoute: DashboardParametersRoute,
  DashboardPhaseFoldingRoute: DashboardPhaseFoldingRoute,
  DashboardPreprocessingRoute: DashboardPreprocessingRoute,
  DashboardReportRoute: DashboardReportRoute,
  DashboardUploadRoute: DashboardUploadRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
